version: '3.5'

networks: 
  localdev:
    name: localdev
    driver: bridge

services:
  api:
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: app/api
      dockerfile: KapaMonitor.Api/Dockerfile
    depends_on: 
      - db-server
    ports:
      - "5000:80"
    networks: 
      - localdev

  client:
    container_name: client
    build: 
      context: app/client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:80"
    networks:
      - localdev

  db-server:
    image: postgres:latest
    container_name: db-server
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Dev123456"
      POSTGRES_DB: "KapaMonitor"
    ports:
      - "5432"
    restart: always
    networks: 
      - localdev
volumes:
  db_volume: