version: '3.5'

networks: 
  localdev:
    name: localdev
    driver: bridge

services:
  KapaMonitor.Api:
    image: ${DOCKER_REGISTRY-}kapamonitorapi
    container_name: api
    build:
      context: .
      dockerfile: KapaMonitor.Api/Dockerfile
    depends_on: 
      - db-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks: 
      - localdev

  db-server:
    image: postgres:latest
    container_name: db-server
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Dev123456"
      POSTGRES_DB: "KapaMonitor"
    ports:
      - "5432"
    restart: always
    networks: 
      - localdev
volumes:
  db_volume: