version: "3.5"

networks:
  local:
    name: local
    driver: bridge

volumes:
  db_volume:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/wwwroot/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/wwwroot/dhparam/
      o: bind


services:
  api:
    image: docker.pkg.github.com/noximi42/kapamonitor/api:latest
    container_name: api
    env_file: 
      - envVars
    networks:
      - local

  client:
    image: docker.pkg.github.com/noximi42/kapamonitor/client:latest
    container_name: client
    networks:
      - local

  website:
    image: docker.pkg.github.com/noximi42/kapamonitor/website:latest
    container_name: website
    networks:
      - local

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./reverse-proxy-nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - website
      - client
      - api
    networks:
      - local

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email kapamonitor@gmail.com --agree-tos --no-eff-email -d kapamonitor.de -d www.kapamonitor.de 