#!bin/bash

sudo docker-compose stop

sudo docker rm api
sudo docker rm client
sudo docker rm website
sudo docker rm proxy

cat github_packages_password | sudo docker login docker.pkg.github.com -u Noximi42 --password-stdin

sudo docker pull docker.pkg.github.com/noximi42/kapamonitor/api:latest
sudo docker pull docker.pkg.github.com/noximi42/kapamonitor/client:latest
sudo docker pull docker.pkg.github.com/noximi42/kapamonitor/website:latest

sudo docker tag docker.pkg.github.com/noximi42/kapamonitor/api api
sudo docker tag docker.pkg.github.com/noximi42/kapamonitor/client client
sudo docker tag docker.pkg.github.com/noximi42/kapamonitor/website website

sudo docker rmi docker.pkg.github.com/noximi42/kapamonitor/api
sudo docker rmi docker.pkg.github.com/noximi42/kapamonitor/client
sudo docker rmi docker.pkg.github.com/noximi42/kapamonitor/website

sudo docker-compose up -d